---
- hosts: local-docker
  tasks:
    - name: Create a directory if it does not exist
      file:
        path: /home/pepesan/deploy
        state: directory
        owner: pepesan
        group: pepesan
        mode: '0755'
    - name: copy Docker Compose files
      copy:
        src: ../files/{{ item }}
        dest: /home/pepesan/deploy/{{ item }}
        owner: pepesan
        group: pepesan
        mode: '0744'
      loop:
        - docker-compose.yaml
    - name: deploy Docker Compose stack
      docker_compose:
        project_src: /home/pepesan/deploy
      register: output
    - name: show debug
      ansible.builtin.debug:
        var: output
    - name: Stop all services
      community.docker.docker_compose:
        project_src: /home/pepesan/deploy
        stopped: yes
      register: output
    - name: show debug
      ansible.builtin.debug:
        var: output
...
