---
- name: Deploy docker container
  hosts: docker
  tasks:
    - name: Install Docker Module for Python
      pip:
        name: docker
    - name: Pull an image
      community.docker.docker_image:
        name: nginx:latest
        source: pull
    - name: Create a volume
      community.docker.docker_volume:
        name: nginx-html-volume
        state: present
    - name: deploy nginx docker container with volume and ports
      community.docker.docker_container:
        image: nginx:latest
        name: nginx
        state: started
        restart: yes
        ports:
          - "80:80"
        volumes:
          - "nginx-html-volume:/var/www/html:rw"
    
...
