---
- hosts: tomcat
  #hosts: localhost # ejecución en local
  #connection: local
  tasks:
    - name: Ensure tomcat10 service is stopped and disabled
      service:
        name: tomcat10
        enabled: no
        state: stopped
    - name: Install required system packages
      package:
        name: 
          - 'default-jdk'
          - 'tomcat10'
        state: absent
        update_cache: no


# ...
