# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.boot_timeout=12000
  # add new hosts, vagrant boxes and give ip to machines
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.hostname="ubuntu"
    ubuntu.vm.box="bento/ubuntu-20.04"
    ubuntu.vm.network "private_network", ip:"192.168.33.10"
  end
end
