---
- name: Desplegar aplicaci칩n con variables cifradas
  hosts: localhost # ejecuci칩n en local
  connection: local
  vars_files:
    - secrets.yaml
  tasks:
    - name: Mostrar la contrase침a de la base de datos
      debug:
        msg: "La contrase침a de la base de datos es {{ db_password }}"