---
- name: Clonar repo Spring Boot en /home/alumno
  hosts: ubuntu

  vars:
    alumno_user: alumno
    repo_url: "https://github.com/pepesan/spring-boot-3.1-api-rest-jpa-testing.git"
    repo_dest: "/home/alumno/spring-boot-3.1-api-rest-jpa-testing"
    repo2_url: "https://github.com/pepesan/ejercicios-selenium-simples.git"
    repo2_dest: "/home/alumno/ejercicios-selenium-simples"

  tasks:
    - name: Asegurar que git está instalado
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: yes

    - name: Clonar el repositorio spring-boot en el home de alumno
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        version: main   # o master si fuera el caso
        update: yes
      become_user: "{{ alumno_user }}"

    - name: Asegurar que los archivos del repo spring-boot pertenecen a alumno
      ansible.builtin.file:
        path: "{{ repo_dest }}"
        state: directory
        recurse: yes
        owner: "{{ alumno_user }}"
        group: "{{ alumno_user }}"
    - name: Clonar el repositorio ejercicios-selenium-simples en el home de alumno
      ansible.builtin.git:
        repo: "{{ repo2_url }}"
        dest: "{{ repo2_dest }}"
        version: master
        update: yes
      become_user: "{{ alumno_user }}"

    - name: Asegurar que los archivos del repo ejercicios-selenium-simples pertenecen a alumno
      ansible.builtin.file:
        path: "{{ repo2_dest }}"
        state: directory
        recurse: yes
        owner: "{{ alumno_user }}"
        group: "{{ alumno_user }}"