---
- name: Clonar repos en /home/alumno
  hosts: ubuntu

  vars:
    alumno_user: alumno
    repo_url: "https://github.com/pepesan/terraform-examples-v2"
    repo_dest: "/home/alumno/terraform-examples-v2"
    repo2_url: "https://github.com/pepesan/ejemplos-kubernetes.git"
    repo2_dest: "/home/alumno/ejemplos-kubernetes"

  tasks:
    - name: Asegurar que git está instalado
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: yes

    - name: Eliminar el directorio del repo docker si ya existe
      ansible.builtin.file:
        path: "{{ repo_dest }}"
        state: absent
    - name: Clonar el repositorio docker en el home de alumno
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        version: master   # o master si fuera el caso
        update: yes
      become_user: "{{ alumno_user }}"

    - name: Asegurar que los archivos del repo docker pertenecen a alumno
      ansible.builtin.file:
        path: "{{ repo_dest }}"
        state: directory
        recurse: yes
        owner: "{{ alumno_user }}"
        group: "{{ alumno_user }}"
    - name: Eliminar el directorio del repo k8s si ya existe
      ansible.builtin.file:
        path: "{{ repo2_dest }}"
        state: absent
    - name: Clonar el repositorio k8s en el home de alumno
      ansible.builtin.git:
        repo: "{{ repo2_url }}"
        dest: "{{ repo2_dest }}"
        version: master
        update: yes
      become_user: "{{ alumno_user }}"

    - name: Asegurar que los archivos del repo k8s pertenecen a alumno
      ansible.builtin.file:
        path: "{{ repo2_dest }}"
        state: directory
        recurse: yes
        owner: "{{ alumno_user }}"
        group: "{{ alumno_user }}"