---
- name: Reinicio de la m치quina
  hosts: ubuntu
  become: true
  tasks:
    - name: Reiniciar el servidor y esperar a que vuelva
      ansible.builtin.reboot:
        reboot_timeout: 600    # tiempo m치ximo de espera (segundos)
        msg: "Reinicio solicitado por Ansible"
        connect_timeout: 5     # espera inicial para reconexi칩n SSH
        test_command: whoami   # comando usado para validar la reconexi칩n