---
- hosts: databases
  tasks:
    - debug:
        msg: play1
    - name: with_list
      ansible.builtin.debug:
        msg: "{{ item }}"
      with_list:
        - one
        - two
    - name: Using dict2items
      ansible.builtin.debug:
        msg: "{{ item.key }} - {{ item.value }}"
      loop: "{{ tag_data | dict2items }}"
      vars:
        tag_data:
          Environment: dev
          Application: payment
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: scripts/miscript.sh
        dest: /home/alumno/myscript.sh
        owner: alumno
        group: alumno
        mode: '0755'
    - name: Retry a task until a certain condition is met
      shell: /home/alumno/myscript.sh
      until: result.stdout.find("Loaded 3 times") != -1
      retries: 5
      delay: 1
      register: result
    - name: Remove file (delete file)
      ansible.builtin.file:
        path: /home/alumno/count.cnt
        state: absent
...
