---
- hosts: webservers
  tasks:
    - name: debug ansible_facts.os_family
      debug:
        msg: "OS Family: {{ ansible_facts.os_family }}"
    - name: Shut down Ubuntu flavored systems
      shell: /sbin/shutdown -t now
      when: ansible_facts['os_family'] == "Debian"
      register: result
    - name: debug result
      debug:
        var: result
        verbosity: 2
...
