---
- hosts: localhost
  connection: local
  vars:
    - list1: [1, 2, 5, 1, 3, 4, 10]
    - list2: [1, 2, 3, 4, 5, 11, 99]
  tasks:
    # Math
    - name: log 01
      debug:
        msg: "{{ 8 | log(10) }}"
    - name: pow 02
      debug:
        msg: "{{ 8 | pow(5) }}"
    - name: root (raiz cuadrada) 03
      debug:
        msg: "{{ 16| root }}"
    - name: root (raiz cuadrática) 04
      debug:
        msg: "{{ 16| root (4) }}"
...
