---
- name: Instalaci贸n desde cero de Docker
  hosts: ubuntu
  #hosts: localhost # ejecuci贸n en local
  #connection: local
  vars:
    docker_ubuntu_codename: "{{ ansible_lsb.codename }}"
  tasks:
    - name: Remove Docker packages
      package:
        name: "{{item}}"
        state: absent
      loop: ['docker', 'docker-engine', 'docker-doc', 'docker.io', 'containerd', 'runc', 'docker-compose-plugin', 'docker-compose', 'docker-compose-v2', 'podman-docker']
    - name: Install required system packages
      package:
        name: 
          - 'apt-transport-https'
          - 'ca-certificates'
          - 'curl'
          - 'software-properties-common'
          - 'python3-pip'
          - 'virtualenv'
          - 'python3-setuptools'
          - 'gnupg'
          - 'lsb-release'
        state: present
        update_cache: yes
      #loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common',
      #'python3-pip', 'virtualenv', 'python3-setuptools', 'gnupg', 'lsb-release']
    - name: Asegurar m贸dulos de kernel necesarios
      modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - overlay
        - br_netfilter

    - name: Configurar sysctl para Docker
      sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        sysctl_set: yes
        state: present
        reload: yes
      loop:
        - { key: net.ipv4.ip_forward, value: 1 }
        - { key: net.bridge.bridge-nf-call-iptables, value: 1 }
    - name: Add Docker GPG apt Key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/trusted.gpg.d/docker.asc
        mode: '0644'
        force: true
    - name: Add Docker Repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/ubuntu {{ docker_ubuntu_codename }} stable"
        state: present
    - name: Install Docker packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop: [ 'docker-ce', 'docker-ce-cli', 'containerd.io','docker-compose-plugin', 'docker-buildx-plugin']
    - name: Ensure docker service is started and enabled
      service:
        name: docker
        enabled: yes
        state: started
    - name: Ensure containerd service is started and enabled
      service:
        name: containerd
        enabled: yes
        state: started
    - name: Install Docker Module for Python
      package:
        name: python3-docker
        state: present
        # update_cache: yes

    - name: Ensure docker group exists
      ansible.builtin.group:
        name: docker
        state: present
    - name: Asegurar que existe el grupo 'alumno'
      ansible.builtin.group:
        name: alumno
        state: present
    - name: Ensure the user 'alumno' with a bash shell, appending the group 'docker' and 'alumno' to the user's groups
      ansible.builtin.user:
        name: alumno
        shell: /bin/bash
        state: present
        groups: alumno,docker
        append: yes
        create_home: yes
        password: '$6$GtOo2iAaz.UZjFbm$H5CeKE3JAKUhh4WaW0ALGEKFRmqI5SgKBsFqrpBOHyEALdARH1a/ynmj9Tdz6KIBhh11GLH2Om4H1xH1bLQMm1'
    - name: Comprobar versi贸n de Docker
      command: docker --version
      register: docker_version
    - debug:
        var: docker_version.stdout
...
