---
- hosts: ubuntu
  tasks:
    - name: Add specified repository into sources list
      ansible.builtin.apt_repository:
        repo: deb http://archive.ubuntu.com/ubuntu focal main restricted
        state: present
    - name: Remove specified repository from sources list
      ansible.builtin.apt_repository:
        repo: deb-src http://archive.ubuntu.com/ubuntu focal main restricted
        state: absent
    - name: Add specified repository into sources list
      ansible.builtin.apt_repository:
        repo: deb http://archive.ubuntu.com/ubuntu focal-updates main restricted
        state: present
    - name: Remove specified repository from sources list
      ansible.builtin.apt_repository:
        repo: deb-src http://archive.ubuntu.com/ubuntu focal-updates main restricted
        state: absent
    - name: Add specified repository into sources list
      ansible.builtin.apt_repository:
        repo: deb http://archive.ubuntu.com/ubuntu focal universe
        state: present
    - name: Remove specified repository from sources list
      ansible.builtin.apt_repository:
        repo: deb-src http://archive.ubuntu.com/ubuntu focal universe
        state: absent
    - name: Add specified repository into sources list
      ansible.builtin.apt_repository:
        repo: deb http://archive.ubuntu.com/ubuntu focal multiverse
        state: present
    - name: Remove specified repository from sources list
      ansible.builtin.apt_repository:
        repo: deb-src http://archive.ubuntu.com/ubuntu focal multiverse
        state: absent
    - name: Add specified repository into sources list
      ansible.builtin.apt_repository:
        repo: deb http://archive.ubuntu.com/ubuntu focal-backports main restricted universe multiverse
        state: present
    - name: Remove specified repository from sources list
      ansible.builtin.apt_repository:
        repo: deb-src http://archive.ubuntu.com/ubuntu focal-backports main restricted universe multiverse
        state: absent
    - name: Add specified repository into sources list
      ansible.builtin.apt_repository:
        repo:  deb http://archive.canonical.com/ubuntu focal partner
        state: absent
    - name: Remove specified repository from sources list
      ansible.builtin.apt_repository:
        repo:  deb-src http://archive.canonical.com/ubuntu focal partner
        state: absent
    - name: Add specified repository into sources list
      ansible.builtin.apt_repository:
        repo: deb http://security.ubuntu.com/ubuntu focal-security main restricted
        state: present
    - name: Remove specified repository from sources list
      ansible.builtin.apt_repository:
        repo: deb-src http://security.ubuntu.com/ubuntu focal-security main restricted
        state: absent
    - name: Add specified repository into sources list
      ansible.builtin.apt_repository:
        repo: deb http://security.ubuntu.com/ubuntu focal-security universe
        state: present
    - name: Remove specified repository from sources list
      ansible.builtin.apt_repository:
        repo: deb-src http://security.ubuntu.com/ubuntu focal-security universe
        state: absent
    - name: Add specified repository into sources list
      ansible.builtin.apt_repository:
        repo: deb http://security.ubuntu.com/ubuntu focal-security multiverse
        state: present
    - name: Remove specified repository from sources list
      ansible.builtin.apt_repository:
        repo: deb-src http://security.ubuntu.com/ubuntu focal-security multiverse
        state: absent
    - name: Add nginx stable repository from PPA and install its signing key on Ubuntu target
      ansible.builtin.apt_repository:
        repo: ppa:nginx/stable
    - name: Remove nginx stable repository from PPA and install its signing key on Ubuntu target
      ansible.builtin.apt_repository:
        repo: ppa:nginx/stable
        state: absent
...
