---
- hosts: databases
  vars:
    - repo_software_packages:
        - software-properties-common
        - dirmngr
        - apt-transport-https
    - key_url: "https://mariadb.org/mariadb_release_signing_key.asc"
    - repo_deb: "deb [arch=amd64] https://dlm.mariadb.com/repo/mariadb-server/10.9/repo/ubuntu"
    - linux_distribution: Ubuntu
    - distribution_release: jammy
    - mariadb_packages:
      - mariadb-server
      - mariadb-common
      - python3-mysqldb
      - python3-openssl
  vars_files: # importación de variables desde fichero
    - vars.yaml
  handlers:
    - name: Flush Priviliges
      command: mysql -u root -p{{ mysql_root_password }} -e "FLUSH PRIVILEGES"
  tasks:
    - name: Set MariaDB root password for 127.0.0.1, localhost
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        host: "{{ item }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
        #login_unix_socket: "{{ mariadb_socket }}"
        state: present
      with_items:
        - 127.0.0.1
        - localhost
      #when: check_passwd_root.rc == 0
      notify: Flush Priviliges
    
    - name: Remove all anonymous user
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: 'test'
        host_all: yes
        state: absent
      notify:
      - Flush Priviliges
    - name: Create Database
      mysql_db:
        name: "{{ database_name }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
        state: present
    - name: Create mysql User defined database
      mysql_user:
        name: "{{ database_user }}"
        password: "{{ database_password }}"
        priv: '{{ database_name }}.*:{{ mysql.privileges }}'
        login_user: root
        login_password: "{{ mysql_root_password }}"
        state: present
      notify:
      - Flush Priviliges
...
