---
- hosts: docker
  tasks:
    - name: Remove Docker packages
      package:
        name: "{{item}}"
        state: absent
      loop: ['docker', 'docker-engine', 'docker.io', 'containerd', 'runc', 'docker-compose']
    - name: Install aptitude using apt
      package:
        name: aptitude
        state: latest
        update_cache: yes
        force_apt_get: yes
    - name: Install required system packages
      package:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common',
      'python3-pip', 'virtualenv', 'python3-setuptools', 'gnupg', 'lsb-release']
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present
    - name: Install Docker packages
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop: [ 'docker-ce', 'docker-ce-cli', 'containerd.io']
    - name: Ensure docker service is started and enabled
      service:
        name: docker
        enabled: yes
        state: started
    - name: Ensure containerd service is started and enabled
      service:
        name: containerd
        enabled: yes
        state: started
    - name: Update apt and install docker-compose
      apt:
        name: docker-compose
        state: latest
    - name: Install Docker Module for Python
      pip:
        name: docker
    - name: Ensure docker group exists
      ansible.builtin.group:
        name: docker
        state: present
    - name: Ensure the user 'pepesan' with a bash shell, appending the group 'docker' and 'pepesan' to the user's groups
      ansible.builtin.user:
        name: alumno
        shell: /bin/bash
        state: present
        groups: alumno,docker
        append: yes

...
